### ISSUE TITLE
How do you package that kind of application for release ?

### ISSUE THREAD

**Issue by topheman** [campoy/flappy-gopher#5]
Hie @campoy ,

I really enjoy your video serie JustForFunc. I started golang a few weeks ago and I made a video game, using sdl2 go bindings (like your flappy-gopher) : [topheman/gopher-ball](https://github.com/topheman/gopher-ball).

I'm on a Mac, it works, no problem. But **how do you build then package** this kind of go application **so that you could distribute a binary** to friends that **don't have go, neither sdl2** intalled ?

You would have to ensure:

- **embedding the assets** (might differ according to the platform - like on Mac OS X `.app` files have some specific folder structure)
- **statically linking the c++ library sdl2** (might need the version of the other platform while compiling cross platform ?) - installed mine with `HomeBrew`
- **compiling cross platform**

While searching,  I've come accross [go-bindata](https://github.com/jteeuwen/go-bindata). Is that the way, isn't there some builtin way to do that (Build flag ? Makefile ?) - it only manage assets (not sdl2 lib).

It's not clear how you should do it and you don't find often repos that go all the way to publishing.

Again, thanks a lot for your videos,

If you have any info about this matter (or if you could point me to some resources that I missed), please do,

Tophe

**Comment by topheman** [comment]
Hie @campoy ,

I managed to make a standalone Mac OS X bundle - not by statically linking the libs at build time with some flags, but after that, by copying the `*.dylib` files and linking them with `install_name_tool -change`.

You can find the full explanation here : https://github.com/topheman/gopher-ball#build

**Comment by campoy** [comment]
That's really cool! 👏

**Comment by topheman** [comment]
Thanks !

Well, I still have some kind of **memory leak** problem to manage https://github.com/topheman/gopher-ball/issues/8 ... The windows build is ready though https://github.com/topheman/gopher-ball/pull/5 .

**Comment by topheman** [comment]
Fixed the memory leak and made the Windows version ! https://github.com/topheman/gopher-ball/releases/tag/v0.3.0
