### ISSUE TITLE
Compatibility issue with veandco/go-sdl2

### ISSUE THREAD

**Issue by nieup** [campoy/flappy-gopher#9]
Seems like the `go-sdl` library is under heavy reconstruction, using `gopkg.in/veandco/go-sdl2.v0` as suggested is not enough to make this work right out of the box: the code there calls on  `github.com/veandco/go-sdl2`. 

Get errors such as this when following the steps in [here](https://github.com/veandco/go-sdl2#installation): 
> ./bird.go:45:34: cannot use r (type *"gopkg.in/veandco/go-sdl2.v0/sdl".Renderer) as type *"github.com/veandco/go-sdl2/sdl".Renderer in argument to img.LoadTexture

Happy to try fixing it, any suggestions?

**Comment by comtom** [comment]
Check my PR. I believe that it fixes this.  https://github.com/campoy/flappy-gopher/pull/10

**Comment by nieup** [comment]
Indeed, it works! 
I dont belive it will be accepted though :/
